core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include('main.urls',namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views 

app_name = 'main'

urlpatterns = [
    path('',views.home,name='home'),
    path('profile/',views.Profile,name='profile')

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

def home(request):
    return render(request,'main/home.html')

@login_required
def Profile(request):
    context = {}
    user = request.user
    context['user'] = user
    return render(request,'main/profile.html',context=context)

main/templates/main/home.html
{% extends 'main/index.html' %}
{% load static %}

{% block subtitle %}
  Home
{% endblock subtitle %}

{% block css %}
  <link rel="stylesheet" href="{% static 'main/css/home.css' %}" />
{% endblock %}

{% block content %}
  <header class="py-2 px-2 d-flex justify-content-between align-items-center animate__animated animate__backInDown">
    <div class="intro d-flex flex-column">
      <span class="syne-64 d-flex">What book you're looking for?</span>
      <span class="syne-16">Explore our catalog and find your next read.</span>
      <div class="d-flex rounded-pill" id="search-container">
        <input type="text" class="px-3 py-1 w-100 rounded-pill" placeholder="type name of book or author" id="q" />
        <button><i class="ph ph-magnifying-glass"></i></button>
      </div>
      <div class="d-flex align-items-baseline">
        <button class="d-flex align-items-center btn btn-yellow mt-4 me-3">
          Explore
          <i class="ph ph-binoculars ms-2"></i>
        </button>
        <div class="line"></div>
      </div>
    </div>
    <div class="image">
      <img src="{% static '/main/assets/images/header-image.jpg' %}" alt="" srcset="" />
    </div>
  </header>
  <section id="trending">
    <div class="section-title">tending books</div>
    <div class="section-content d-flex border rounded-3 p-3 border-dark">
      <div class="book">
        <img src="https://images.booksense.com/images/157/342/9781441342157.jpg" />
        <div class="book-details">
          <h6>Book Name</h6>
          <div class="author">
            <strong>by :</strong>author
          </div>
          <div class="description">
            <strong>description</strong> <br />
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
          </div>
        </div>
      </div>
      <div class="book">
        <img src="https://www.georgerrmartin.com/wp-content/uploads/2013/03/GOTMTI2.jpg" />
        <div class="book-details">
          <h6>Book Name</h6>
          <div class="author">
            <strong>by :</strong>author
          </div>
          <div class="description">
            <strong>description</strong> <br />
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis officiis, assumenda et accusantium nemo cupiditate iusto numquam aliquid quidem consequatur quas pariatur architecto, velit consequuntur veniam unde illum repellat alias beatae ab totam, amet ullam enim excepturi? Nisi, cupiditate minus porro et reprehenderit alias dolore.
            </p>
          </div>
        </div>
      </div>
      <div class="book">
        <img src="https://marketplace.canva.com/EAFaQMYuZbo/1/0/1003w/canva-brown-rusty-mystery-novel-book-cover-hG1QhA7BiBU.jpg" />
        <div class="book-details">
          <h6>Book Name</h6>
          <div class="author">
            <strong>by :</strong>author
          </div>
          <div class="description">
            <strong>description</strong> <br />
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
          </div>
        </div>
      </div>
      <div class="book">
        <img src="https://images.penguinrandomhouse.com/cover/9780593422182" />
        <div class="book-details">
          <h6>Book Name</h6>
          <div class="author">
            <strong>by :</strong>author
          </div>
          <div class="description">
            <strong>description</strong> <br />
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
          </div>
        </div>
      </div>
      <div class="book">
        <img src="https://bukovero.com/wp-content/uploads/2016/07/Harry_Potter_and_the_Cursed_Child_Special_Rehearsal_Edition_Book_Cover.jpg" />
        <div class="book-details">
          <h6>Book Name</h6>
          <div class="author">
            <strong>by :</strong>author
          </div>
          <div class="description">
            <strong>description</strong> <br />
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="categories">
    <div class="section-title">Our Categories</div>
    <div class="section-content d-flex">
        <a class="btn">Category</a>
        <a class="btn">Category</a>
        <a class="btn">Category</a>
        <a class="btn">Category</a>
        <a class="btn">Category</a>
        <a class="btn">Category</a>
    </div>
  </section>
  <section id="authors">
    <span class="section-title">
        authors
    </span>
    <div class="section-content">
        <div id="author" class="d-flex flex-column">
            <img src="{% static 'main\assets\images\author.png' %}" alt="Author Name">
            <h6 class="syne-16">Lorem, ipsum dolor.</h6>
        </div>
        <div id="author" class="d-flex flex-column">
            <img src="{% static 'main\assets\images\author.png' %}" alt="Author Name">
            <h6 class="syne-16">Lorem, ipsum dolor.</h6>
        </div>
        <div id="author" class="d-flex flex-column">
            <img src="{% static 'main\assets\images\author.png' %}" alt="Author Name">
            <h6 class="syne-16">Lorem, ipsum dolor.</h6>
        </div>
        <div id="author" class="d-flex flex-column">
            <img src="{% static 'main\assets\images\author.png' %}" alt="Author Name">
            <h6 class="syne-16">Lorem, ipsum dolor.</h6>
        </div>
        <div id="author" class="d-flex flex-column">
            <img src="{% static 'main\assets\images\author.png' %}" alt="Author Name">
            <h6 class="syne-16">Lorem, ipsum dolor.</h6>
        </div>
    </div>
  </section>
  <section id="news-letter">
    <span class="section-title">Our News Letter</span>
    <div class="section-content d-flex justify-content-center align-items-center flex-wrap">
        <i class="ph ph-paper-plane-tilt"></i>
        <div class="description d-flex flex-column">
            <h5 class="syne-18">Subscribe to our newlettre to get the latest books for free</h5>
            <form action="" class="d-flex">
                <input type="email" name="email" id="email" placeholder="E-mail adress">
                <button class="btn" type="submit">Subscribe</button>
            </form>
        </div>
        
    </div>
  </section>
{% endblock %}

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% comment %}Meta Tags{% endcomment %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="A Book Store like you've never seen before" />
    <meta name="keywords" content="book,books,store,novels" />
    <meta name="author" content="Amraoui Mohamed" />
    <link rel="shortcut icon" href="{% static '/main/assets/images/LOGO_ICON.svg' %}" type="image/x-icon" />
    <meta name="theme-color" content="#ffffff" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    {% comment %}Unica One Font{% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Unica+One&display=swap" rel="stylesheet" />
    {% comment %}Syne Font{% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400..800&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}" />

    {% block css %}

    {% endblock %}
    <title>
      Book Store |{% block subtitle %}

      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container-xxl">
      {% block nav %}
        <nav class="d-flex justify-content-between align-items-center bg-white py-4 px-2">
          <a class="logo d-flex align-items-center" href="{% url 'main:home' %}"><img src="{% static 'main/assets/images/LOGO.png' %}" alt="Site Logo" /></a>
          <ul class="align-items-center p-0" id="nav-menu">
            <h4 class="unica-24 w-100">Our Main Menu</h4>
            <li class="nav-item">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shop</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact Us</a>
            </li>
          </ul>
          <div class="nav-actions d-flex align-items-center">
            <a href="">
              <i class="ph ph-shopping-cart-simple"></i>
              <span class="cart-items">0</span>
            </a>
            <div class="d-flex flex-column position-relative">
              <button class="menu-button"><i class="ph ph-user-circle"></i></button>

              <ul class="menu-list rounded bg-white shadow" id="external-menu">
                {% if request.user.is_authenticated %}
                  <li>
                    <a href="{% url 'main:profile' %}">My Profile</a>
                  </li>
                  <hr />
                  <li>
                    <a href="{% url 'account_logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li>
                    <a href="{% url 'account_login' %}">login</a>
                  </li>
                  <li>
                    <a href="{% url 'account_signup' %}">signup</a>
                  </li>
                {% endif %}
              </ul>
            </div>
            <button id="nav-button"><i class="ph ph-list"></i></button>
          </div>
        </nav>
      {% endblock %}
      {% block content %}

      {% endblock %}
      {% block footer %}
        <footer class="py-5 px-2 bg-white d-flex justify-content-between align-items-center">
          <div>
            <span class="syne-16">by Amraoui Mohamed &copy; 2024</span>
          </div>
          <span class="social-media d-flex align-items-center">
            <a href=""><i class="ph ph-linkedin-logo"></i></a>
            <a href=""><i class="ph ph-github-logo"></i></a>
            <a href=""><i class="ph ph-figma-logo"></i></a>
          </span>
        </footer>
      {% endblock %}
    </div>
    {% block js %}

    {% endblock %}
    <script src="https://unpkg.com/@phosphor-icons/web"></script>

    <script src="{% static 'main/js/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/profile.html
{% extends 'main/index.html' %}
{% load static %}

{% block subtitle %}
  Home
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'main/css/profile.css' %}" />
{% endblock %}


{% block content %}
  <section id="userprofile" class="d-flex flex-row">
    <ul class="nav nav-pills mb-3cd-flex " id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">
        <i class="ph ph-house"></i>
          Home
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Profile</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Contact</button>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">...</div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
      <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">...</div>
    </div>

{% endblock content %}

{% block footer %}

{% endblock %}